apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecs-reader
rules:
  - apiGroups: ["ecs.aws.upbound.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["ec2.aws.upbound.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["elbv2.aws.upbound.io"] # "" indicates the core API group
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecs-backstage-reader
subjects:
  - kind: ServiceAccount
    name: tap-gui-viewer
    namespace: tap-gui
roleRef:
  kind: ClusterRole
  name: ecs-reader
  apiGroup: rbac.authorization.k8s.io